// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameJob = "job"

// Job mapped from table <job>
type Job struct {
	JobID              int64      `gorm:"column:job_id;type:bigint unsigned;primaryKey;comment:任务id" json:"job_id"`
	PrepareExecuteTime time.Time  `gorm:"column:prepare_execute_time;type:datetime;not null;comment:预期执行时间" json:"prepare_execute_time"`
	JobStatus          int8       `gorm:"column:job_status;type:tinyint;not null;comment:任务状态" json:"job_status"`
	ExecuteTime        *time.Time `gorm:"column:execute_time;type:datetime;comment:最终执行时间" json:"execute_time"`
	Tag                string     `gorm:"column:tag;type:varchar(255);not null;default:{};comment:任务标签，用在回调" json:"tag"`
}

// TableName Job's table name
func (*Job) TableName() string {
	return TableNameJob
}
